name: BuildPortals
main: frahm.justin.mcplugins.buildportals.Main
version: 0.0.1
commands:
  buildportals:
    description: All commands for the BuildPortals plugin.
  bp:
    description: All commands for the BuildPortals plugin.
    