name: BuildPortals
main: frahm.justin.mcplugins.buildportals.Main
version: ___
softdepend:
  - Multiverse-Core
  - Multiworld
commands:
  buildportals:
    description: All commands for the BuildPortals plugin.
  bp:
    description: All commands for the BuildPortals plugin.
permissions:
  buildportals.*:
    description: Gives access to all BuildPortals commands
    default: op
    children:
      buildportals.listmaterials: true
  buildportals.listactivators:
    description: Give access to the activator material list.
    default: true
  buildportals.activate:
    description: Can activate a new portal
    default: true
  buildportals.teleport:
    description: Can use a portal
    default: true
